### ISSUE TITLE
 ROBUST HYPORADISE DATASET training splits

### ISSUE THREAD

**Issue by Sreyan88** [YUCHEN005/RobustGER#1]
Hello,

Great work! I wanted to ask for the  ROBUST HYPORADISE DATASET training splits. I checked the HF page linked in README, and it looks like only the test sets were released. Any help would be appreciated!

Thank You again!

**Comment by YUCHEN005** [comment]
Hi, Thanks for interest in our work. Sorry for inconvenience.

The training split is large and thus now still in package, i'll release the link to drive in hf once available, hope can complete next month.

**Comment by huckiyang** [comment]
@YUCHEN005 let's release the RobustGER training script in Huggingface with large space limit.

**Comment by MrigankRaman** [comment]
@YUCHEN005 Any ETA on the train split?

**Comment by YUCHEN005** [comment]
Hi all, sorry for delay, please see our new update in [huggingface](https://huggingface.co/datasets/PeacefulData/Robust-HyPoradise). Thank you!

**Comment by huckiyang** [comment]
this issue can be closed. @YUCHEN005
