### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by Sreyan88** [YUCHEN005/RobustGER#2]
Hello,

Great work! I face this error while running `finetune.sh`:

```
from lit_gpt.model import KVCache, RoPECache, apply_rope
ImportError: cannot import name 'RoPECache' from 'lit_gpt.model'
```

any help would be appreciated!

**Comment by YUCHEN005** [comment]
Hello,

Thank you for attention and pointing out this. It could be due to the fast iterating versions of lit-gpt --> `RoPECache` may be defined in an old version and already deprecated now.

To solve it, you may remove this import of `RoPECache` and replace all of them with `torch.tensor` in the code. Because the computation of rope position embedding is done by function `build_rope_cache` in `lit_gpt/model.py`, which is unrelated to `RoPECache`.

Sorry I am outside and unaccessible to our server this week, I will check my running code later and update you if any new findings.

**Comment by YUCHEN005** [comment]
Hi, thanks for reporting this.

The problem is the version change between latest lit-git and what I used last year --> Previous code is the latest lit-gpt, which does not fit my code.

Now I have uploaded the old version of lit-git that I used before.

Sorry for inconvenience, welcome to report further issues.

**Comment by Learneducn** [comment]
很抱歉再次打扰到您，对您的研究非常感兴趣，一值都在努力学习您的研究方向，但在尝试复现的过程中，还是遇到了一些问题，但是我在执行第一步convert_lit_model.py的时候就报错了，请问你们使用的是llama-7b-hf模型吗。还有请问你们的训练数据转换为.pt文件的脚本有开源吗，想训一些自己的参数。万分感谢！！

**Comment by YUCHEN005** [comment]
Hi, thanks for reporting these.

1. We use 3 llama versions in this work: llama-2-7b-hf, llama-2-13b-hf, llama-7b-hf, where lit-git repo only support llama-2 versions, while llama is supported by lit-llama repo. Our code here follows lit-gpt.

2. We have released the script on huggingface: https://huggingface.co/datasets/PeacefulData/Robust-HyPoradise (see our UPDATE in readme)

Hope that works for you.

**Comment by Learneducn** [comment]
Thank you very much for taking the time out of your busy schedule to reply to me.
&nbsp; &nbsp; &nbsp; I have seen a lot of your team's work on the website and am very interested in your research. I have recently tried to reproduce your paper 《HyPoradise: An Open Baseline for Generative Speech Recognition with Large Language Models》, but I have not found the reasoning script. If it is convenient, could you share your infer script with me?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YUCHEN005/RobustGER"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月29日(星期一) 下午2:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YUCHEN005/RobustGER] Error while running (Issue #2)





 
Hi, thanks for reporting these.
  
 
We use 3 llama versions in this work: llama-2-7b-hf, llama-2-13b-hf, llama-7b-hf, where lit-git repo only support llama-2 versions, while llama is supported by lit-llama repo. Our code here follows lit-gpt.
 
 
 
We have released the script on huggingface: https://huggingface.co/datasets/PeacefulData/Robust-HyPoradise
 
  
Hope that works for you.

**Comment by YUCHEN005** [comment]
Hi, thanks for reporting this. We have updated the inference script in original repo.

**Comment by Learneducn** [comment]
I'm so sorry to bother you again. Thank you very much for taking the time to reply to me despite your busy schedule. When I was using the inference script you shared with me yesterday for inference, this error occurred again. How did you solve it? Hope you can share your experience for me.



------------------ 原始邮件 ------------------
发件人:                                                                                                                        "YUCHEN005/RobustGER"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月5日(星期天) 下午5:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YUCHEN005/RobustGER] Error while running (Issue #2)





 
Hi, thanks for reporting this. We have updated the inference script in original repo.

**Comment by YUCHEN005** [comment]
Hi, can you specify running which script produce which bug? --> The inference script I shared yesterday is on original GER repo (if bug, can you lanuch an Issue there?), which is based on transformers+peft packages instead of lit-gpt.

The RoPE_cache error should be resolved now. Its definition is at: https://github.com/YUCHEN005/RobustGER/blob/master/lit_gpt/model.py#L16

**Comment by Learneducn** [comment]
I'm really glad to receive your response. The problems I currently encounter are as follows (I am currently doing experiments on the llama-7b-hf LLM from huggingface):
&nbsp; &nbsp;1)While trying to reproduce this paper 《HyPoradise: An Open Baseline for Generative Speech Recognition with Large Language Models》，The pre-training model I used is llama-7b-hf ， now I have completed the fine-tuning followed the open source tutorial and saved the following model weights. Could you please help me check if there is any problem with the format of the generated model? When I use your script for inference,When doing the inference an error was reported. The error result is as shown in the figure3 below. Also,&nbsp; I hope you can share your environment variable file&nbsp; 'requirements.txt'&nbsp; with me. I want to see if there is an issue with the environment configuration.




&nbsp; &nbsp;2)While trying to reproduce this paper 《LARGE LANGUAGE MODELS ARE EFFICIENT LEARNERS OF NOISE-ROBUST SPEECH RECOGNITION》，When executing the convert_lit_checkpoint.py script of ‘RobustGER’, the model cannot be converted.&nbsp;I would like to ask how you convert llama-7b-hf to "lit_model.pth"&nbsp; and "lit_config.json".The contents of the model folder of the LLM from huggingface&nbsp;I use are as shown below.

&nbsp; I'm so sorry to bother you again, looking forward to your reply.



------------------ 原始邮件 ------------------
发件人:                                                                                                                        "若柒"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月6日(星期一) 下午3:34
***@***.***&gt;;

主题:&nbsp;回复： [YUCHEN005/RobustGER] Error while running (Issue #2)



I'm so sorry to bother you again. Thank you very much for taking the time to reply to me despite your busy schedule. When I was using the inference script you shared with me yesterday for inference, this error occurred again. How did you solve it? Hope you can share your experience for me.



------------------ 原始邮件 ------------------
发件人:                                                                                                                        "YUCHEN005/RobustGER"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月5日(星期天) 下午5:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YUCHEN005/RobustGER] Error while running (Issue #2)





 
Hi, thanks for reporting this. We have updated the inference script in original repo.

**Comment by YUCHEN005** [comment]
Hi, there are some issues, let me claim:

- The Hyporadise repo is done on llama-7b (LLaMA-1), which is implemented using transformers+peft packages, you just need to use "from_pretrained" function to load llm weights from huggingface (no extra operations needed). 

- The RobustGER repo is done on llama-2-7b/13b (LLaMA-2), which is implemented using lit-git toolkit, here you need to convert the hf-format model to lightning format.

For your questions:

1. I have just upload the requirements.txt in Hyporadise repo, please check [there](https://github.com/Hypotheses-Paradise/Hypo2Trans/blob/main/requirements.txt). Btw, I cannot receive the email nor the figure, can you post it in GitHub issue directly?
2. The issue is, the "llama-7b-hf" you use is LLaMA-1, here our code (following lit-gpt) only support LLaMA-2.

Hope these helps.

**Comment by Learneducn** [comment]
&nbsp; &nbsp; I'm very sorry to bother you again. I'm very interested in your research, so I keep asking you questions and causing you a lot of inconvenience. I'm very sorry.
&nbsp; &nbsp; &nbsp;The models I use now is llama-2-7b-hf.&nbsp;The problems I am currently encountering are as follows:
&nbsp; &nbsp;1)&nbsp; On Hyporadise framework I also used the llama-2-7b-hf model and&nbsp; I finished the fine-tuning according to the tutorial, but the model failed to load and produced a&nbsp;wrong during inference as : "with safe open(filename, framework="pt", device=device) as f:safetensors rust .SafetensorError: Error while deserializing header: InvalidHeaderDeserialization"
&nbsp; 2) On RobustGER repo , When I execute a script ' python scripts/convert_lit_checkpoint.py '&nbsp; to convert the model according to the tutorial, the following error message always appears:&nbsp;error: Validation failed: No action for key "_name_or_path" to check its value.
&nbsp; &nbsp;If it is convenient for you, can you share your converted model files of lit-gpt.pth and lit-gpt.json? Thank you very much.
&nbsp; &nbsp;
&nbsp; &nbsp; I am very glad to receive your letter, and I am very interested in your current research field. I'm sorry to bother you again. I encountered some problems when I tried to reproduce your paper. Perhaps my expression was not clear enough, and it was not convenient to describe my problems by email. With all due respect, If it is convenient for you, can you add a contact information? My wechat&nbsp; number is "YY-780757250". If it is convenient for you, you can also send me your contact information privately. I hope I can ask you more questions.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "若柒"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月6日(星期一) 下午5:44
***@***.***&gt;;

主题:&nbsp;回复： [YUCHEN005/RobustGER] Error while running (Issue #2)



I'm really glad to receive your response. The problems I currently encounter are as follows (I am currently doing experiments on the llama-7b-hf LLM from huggingface):
&nbsp; &nbsp;1)While trying to reproduce this paper 《HyPoradise: An Open Baseline for Generative Speech Recognition with Large Language Models》，The pre-training model I used is llama-7b-hf ， now I have completed the fine-tuning followed the open source tutorial and saved the following model weights. Could you please help me check if there is any problem with the format of the generated model? When I use your script for inference,When doing the inference an error was reported. The error result is as shown in the figure3 below. Also,&nbsp; I hope you can share your environment variable file&nbsp; 'requirements.txt'&nbsp; with me. I want to see if there is an issue with the environment configuration.




&nbsp; &nbsp;2)While trying to reproduce this paper 《LARGE LANGUAGE MODELS ARE EFFICIENT LEARNERS OF NOISE-ROBUST SPEECH RECOGNITION》，When executing the convert_lit_checkpoint.py script of ‘RobustGER’, the model cannot be converted. I would like to ask how you convert llama-7b-hf to "lit_model.pth"&nbsp; and "lit_config.json".The contents of the model folder of the LLM from huggingface I use are as shown below.

&nbsp; I'm so sorry to bother you again, looking forward to your reply.



------------------ 原始邮件 ------------------
发件人:                                                                                                                        "若柒"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月6日(星期一) 下午3:34
***@***.***&gt;;

主题:&nbsp;回复： [YUCHEN005/RobustGER] Error while running (Issue #2)



I'm so sorry to bother you again. Thank you very much for taking the time to reply to me despite your busy schedule. When I was using the inference script you shared with me yesterday for inference, this error occurred again. How did you solve it? Hope you can share your experience for me.



------------------ 原始邮件 ------------------
发件人:                                                                                                                        "YUCHEN005/RobustGER"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月5日(星期天) 下午5:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YUCHEN005/RobustGER] Error while running (Issue #2)





 
Hi, thanks for reporting this. We have updated the inference script in original repo.
