### ISSUE TITLE
When will the code be updated

### ISSUE THREAD

**Issue by xuridongsheng7142** [YUCHEN005/RobustGER#3]
This is a good piece of work, thanks to the author, but there are still some errors in the code. When will the code be updated?

**Comment by YUCHEN005** [comment]
Hi, thanks for report. Can you specifiy the errors you meet so that I can update them together. Thank you!

**Comment by xuridongsheng7142** [comment]
Hi, thank you for your prompt response.

The error I encountered is:   AttributeError: 'GPT' object has no attribute 'build_rope_cache'.
Additionally, I found that 'build_mask_cache' and 'build_kv_caches' are not defined as well.

Thank you for your assistance!

**Comment by Learneducn** [comment]
请问作者什么时候更新代码呢，无法运行，有很多的库调用不到

**Comment by YUCHEN005** [comment]
Hi, thanks for reporting this.

The problem is the version change between latest lit-git and what I used last year --> Previous code is the latest lit-gpt, which does not fit my code.

Now I have uploaded the old version of lit-git that I used before.

Sorry for inconvenience, welcome to report further issues.

**Comment by Learneducn** [comment]
Hello, excuse me. When I follow the tutorial and use your script to convert the llama-2-7b-hf model, the following error always appears. I don’t know how to solve it.
[root@localhost RobustGER-master]# sh conv_model.sh
usage: convert_lit_checkpoint.py [-h] [--config CONFIG] [--print_config[=flags]]
--checkpoint_name CHECKPOINT_NAME --out_dir OUT_DIR
--model_name MODEL_NAME
error: Validation failed: No action for key "_name_or_path" to check its value.
